# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: mkdir rune && cd rune && curl -OL https://github.com/hotg-ai/rune/releases/download/nightly/rune.x86_64-unknown-linux-gnu.zip && unzip rune.x86_64-unknown-linux-gnu.zip && chmod +x rune && sudo mv rune /usr/local/bin/ # runs during prebuild
    command: echo "Rune done"
  - init: pip3 install numpy Pillow
    command: echo "ready"
  - init: sudo apt-get install -y unzip wget
    command: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && sudo chmod +x ngrok && sudo mv ngrok /usr/local/bin/ && rm ngrok-stable-linux-amd64.zip
  - init: curl -OL https://github.com/hotg-ai/rune-serve/releases/download/hackathon/rune-serve-linux-amd64.zip && unzip rune-serve-linux-amd64.zip && sudo chmod +x rune-serve && sudo mv rune-serve /usr/local/bin/ && rm rune-serve-linux-amd64.zip
    command: echo "Rune Serve done"
  

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
