# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: mkdir rune && cd rune && curl -OL https://github.com/hotg-ai/rune/releases/download/v0.10.0/rune.x86_64-unknown-linux-gnu.zip # runs during prebuild
    command: unzip rune.x86_64-unknown-linux-gnu.zip && mv rune ~/.cargo/bin && cd ~/.cargo/bin && chmod +x rune && cd /workspace/tutorials && clear

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview